name: Build and Test Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t task-manager .
      
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 task-manager
          
      - name: Test application (you can write tests using curl or similar)
        run: |
          sleep 10
          curl http://localhost:5000  # Check if the app is running
          
      - name: Stop Docker container
        run: |
          docker ps -q | xargs docker stop
