name: Build and Test Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t task-manager .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 task-manager  # Run container in detached mode
          docker ps -a  # Check running containers
          
      - name: Get Docker container logs
        run: |
          # Get the container name from docker ps and then fetch the logs of that container
          container_id=$(docker ps --filter "ancestor=task-manager" -q)  # Get the container ID of the task-manager image
          docker logs $container_id  # Fetch logs from the container

      - name: Wait for the Flask app to be available
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "Flask app is up and running!"
              break
            fi
            echo "Waiting for Flask app to be ready..."
            sleep 3
          done

      - name: Test application
        run: |
          curl http://localhost:5000

      - name: Stop Docker container
        run: |
          docker ps -q | xargs docker stop
