name: Build, Test, and Push Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest  # Run container in detached mode
          docker ps -a  # Check running containers
          
      - name: Get Docker container logs
        run: |
          # Get the container ID of the task-manager image and fetch the logs
          container_id=$(docker ps --filter "ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/task-manager:latest" -q)
          docker logs $container_id  # Fetch logs from the container

      - name: Wait for the Flask app to be available
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "Flask app is up and running!"
              break
            fi
            echo "Waiting for Flask app to be ready..."
            sleep 3
          done

      - name: Test application
        run: |
          curl http://localhost:5000

      - name: Stop Docker container if running
        run: |
          container_id=$(docker ps -q)
          if [ -n "$container_id" ]; then
            echo "Stopping Docker container..."
            docker stop $container_id
          else
            echo "No running containers to stop."
          fi
